### ISSUE TITLE
Change issue type icon on problem details

### ISSUE THREAD

**Issue by ghost** [CodeTanzania/open311-web-public#10]
<img width="264" alt="screen shot 2018-04-24 at 09 48 24" src="https://user-images.githubusercontent.com/6306014/39170556-afac8a52-47a4-11e8-8573-fed4613c28cc.png">

It should have the same icons used in Issue Type filter. 

<img width="330" alt="screen shot 2018-04-24 at 09 49 11" src="https://user-images.githubusercontent.com/6306014/39170581-c8a920ec-47a4-11e8-8afb-c8d7b22afcb3.png">

**Comment by kasongoyo** [comment]
From the snapshot, it seems the icon for request other is the same? @jeanbarroca

**Comment by ghost** [comment]
You need to change the external color of the cycle to make it coherent with
filter & markers colors.

**Comment by kasongoyo** [comment]
I get it now. Thanks
