### ISSUE TITLE
Unable to lunch application in development mode

### ISSUE THREAD

**Issue by Mloweedgar** [CodeTanzania/open311-web-public#27]
After succefully running npm install the app doesnot open in development mode when npm run dev is executed. 
![error](https://user-images.githubusercontent.com/12539814/40350232-df0767c2-5db1-11e8-9ea1-40166b8b5427.png)

**Comment by kasongoyo** [comment]
@Mloweedgar This project depends on some environmental variables so you need to set them before starting the app. I need to update the README file to cover this issue. For the time being set `PUBLICWEB_AUTH_TOKEN` locally to be able to run the app.

**Comment by Mloweedgar** [comment]
thanks for the reply @kasongoyo , I have used this work around https://github.com/CodeTanzania/open311-web-public/pull/28. you can look at it
